version: '3.5'
services:
  donuts.rabbit:
    build: ./
    image: streamline27/donuts.rabbit:latest
    container_name: donuts.rabbit
    ports:
      - "9010:9010"
    environment:
      - "spring.profiles.active=docker"