spring:
  application:
    name: rabbit
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
          dataSourceClassName: org.h2.jdbcx.JdbcDataSource
          url: jdbc:h2:file:./h2-db
          username: ca
server:
  port: 9010
  servlet:
    context-path: /rabbit
