spring:
  application:
    name: rabbit
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
      url: jdbc:h2:file:./h2/h2-db
      username: ca
  rabbitmq:
    host: 192.168.188.104
    port: 5672
    virtual-host: /
    username: vladja
    password: Password1
server:
  port: 9010
  servlet:
    context-path: /rabbit
